### ISSUE TITLE
Getting "You may need an appropriate loader" error after adding external code dependency

### ISSUE THREAD

**Issue by rooskienz** [ModusCreateOrg/react-dynamic-route-loading-es6#13]
Hi,

**this is not an issue with the code in this repo** but rather an issue with the next step for this solution. When trying to import an external code as a dependency, and then importing it in one of the routes I get the "You may need an appropriate loader" on the external code where it tries to return some JSX code, it seems like it doesn't recognise JSX code inside of that module that's brought in as a dependency, I'm not an expert on webpack so maybe there is an extra step that I'm missing here?

Any help?

**Comment by grgur** [comment]
Thanks for reporting, I need to update for the latest version of Webpack

**Comment by grgur** [comment]
Fixed that and upgraded all packages. Thanks!
