### ISSUE TITLE
error: options/query provided without loader (use loader + options) in {

### ISSUE THREAD

**Issue by kimown** [ModusCreateOrg/react-dynamic-route-loading-es6#14]
After I pull the project, when I run `npm run start`, the error occurs, log is here
```
Error: options/query provided without loader (use loader + options) in {
  "test": {},
  "use": "file-loader",
  "query": {
    "name": "[name].[ext]"
  }
}

```

so I think the . html  [rule](https://github.com/ModusCreateOrg/react-dynamic-route-loading-es6/blob/73cf2cfb2f764ece8f1af012f06b1de22e7d9938/webpack.config.js#L74])

should be
```
      {
        test: /\.html$/,
        use: [{
          loader:'file-loader',
          query: {
            name: '[name].[ext]'
          }
        }],
      },
```
Finally, thank you for you example. 😄

**Comment by grgur** [comment]
You're right, I need to align it with the new Webpack release.

**Comment by grgur** [comment]
Fixed that and upgraded all packages. Thanks for reporting!
