### ISSUE TITLE
Support CSS code Splitting

### ISSUE THREAD

**Issue by monkindey** [ModusCreateOrg/react-dynamic-route-loading-es6#19]
The https://burning-heat-4609.firebaseapp.com/ website only split the JS code,

But sometime different router have huge CSS, Maybe we can support CSS code splitting.

Any Thought?

**Comment by grgur** [comment]
if you use [ExtractTextPlugin](https://github.com/webpack-contrib/extract-text-webpack-plugin) you can use `allChunks: true` to bundle all of the css in one big file, or leave it `false` to bundle css as part of code-split js modules

**Comment by monkindey** [comment]
Thanks for your reply. I'll try it.
