### ISSUE TITLE
Chunk.entry was removed. Use has Runtime()

### ISSUE THREAD

**Issue by gagayang** [ModusCreateOrg/react-dynamic-route-loading-es6#3]
i was try your demo, but find an erroy with "Chunk.entry was removed. Use has Runtime()", do you know this error? and how to fix it?

**Comment by ArjanJ** [comment]
I get this error too.

**Comment by anatoliyg** [comment]
`npm i webpack@2.1.0-beta.8 extract-text-webpack-plugin@1.0.1` seems to do the trick, per
https://github.com/Hashnode/mern-starter/issues/200

**Comment by mihirsoni** [comment]
I have opened PR , which should fix the error.
