### ISSUE TITLE
How to connect Redux?

### ISSUE THREAD

**Issue by justinireland** [ModusCreateOrg/react-dynamic-route-loading-es6#8]
I see your actions folder but I don't see how you've connected Redux in this example. I'm having trouble getting it working in my adaptation so that's why I'm wondering how it should be done.

**Comment by grgur** [comment]
Head over to the [Budgeting App](https://github.com/ModusCreateOrg/budgeting-sample-app-webpack2), a much more up-to-date example with Redux included
